# Generated by Django 2.1.3 on 2018-12-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=6)),
                ('accuracy', models.IntegerField()),
            ],
        ),
    ]
