# Generated by Django 2.1.3 on 2018-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
